/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMoreContent: typeof import('./src/components/AddNew/AddMoreContent.vue')['default']
    AddNewContentCom: typeof import('./src/components/AddNew/AddNewContentCom.vue')['default']
    AddOneContent: typeof import('./src/components/AddNew/AddOneContent.vue')['default']
    copy: typeof import('./src/components/WifiKeyBoard copy.vue')['default']
    DebugDetail: typeof import('./src/components/Debug/DebugDetail.vue')['default']
    DebugGrab: typeof import('./src/components/Debug/DebugGrab.vue')['default']
    DebugNormal: typeof import('./src/components/Debug/DebugNormal.vue')['default']
    DebugOffset: typeof import('./src/components/Debug/DebugOffset.vue')['default']
    DebugTab: typeof import('./src/components/Debug/DebugTab.vue')['default']
    DetailDetail: typeof import('./src/components/Detail/DetailDetail.vue')['default']
    DetailNormal: typeof import('./src/components/Detail/DetailNormal.vue')['default']
    DetailSetting: typeof import('./src/components/Detail/DetailSetting.vue')['default']
    DetailSwiper: typeof import('./src/components/DetailSwiper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HomeSwiper: typeof import('./src/components/HomeSwiper.vue')['default']
    KeyBoard: typeof import('./src/components/KeyBoard.vue')['default']
    KeyBoardEn: typeof import('./src/components/KeyBoardEn.vue')['default']
    KeyBoardSetting: typeof import('./src/components/KeyBoardSetting.vue')['default']
    KeyBoardUser: typeof import('./src/components/KeyBoardUser.vue')['default']
    NumKeyBoard: typeof import('./src/components/NumKeyBoard.vue')['default']
    NumKeyBoardAdd: typeof import('./src/components/AddNew/NumKeyBoardAdd.vue')['default']
    NumKeyBoardHome: typeof import('./src/components/NumKeyBoardHome.vue')['default']
    NumKeyBoardNormal: typeof import('./src/components/NumKeyBoardNormal.vue')['default']
    NumKeyBoardUser: typeof import('./src/components/NumKeyBoardUser.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    'Panel稳定': typeof import('./src/components/Panel稳定.vue')['default']
    PanelUser: typeof import('./src/components/PanelUser.vue')['default']
    RightClick: typeof import('./src/components/Debug/RightClick.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/Scroll.vue')['default']
    ScrollLeft: typeof import('./src/components/ScrollLeft.vue')['default']
    ScrollLeftNew: typeof import('./src/components/ScrollLeftNew.vue')['default']
    ScrollNew: typeof import('./src/components/ScrollNew.vue')['default']
    SettingContent: typeof import('./src/components/Pallet/SettingContent.vue')['default']
    StackingContent: typeof import('./src/components/Pallet/StackingContent.vue')['default']
    TabNormal: typeof import('./src/components/Pallet/TabNormal.vue')['default']
    TabNormalContent: typeof import('./src/components/Pallet/TabNormalContent.vue')['default']
    TabSwiper: typeof import('./src/components/TabSwiper.vue')['default']
    'TabSwiper模版': typeof import('./src/components/TabSwiper模版.vue')['default']
    TabSwiperSetting: typeof import('./src/components/TabSwiperSetting.vue')['default']
    WifiKeyBoard: typeof import('./src/components/WifiKeyBoard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
